import os
import struct
from supabase import create_client, Client
from datetime import datetime
import uuid
from dotenv import load_dotenv

load_dotenv()

class SupabaseDB:
    def __init__(self):
        url: str = os.environ.get("SUPABASE_URL")
        key: str = os.environ.get("SUPABASE_KEY")
        if not url or not key:
            raise ValueError("SUPABASE_URL and SUPABASE_KEY must be set in your .env file!")
        print("[DB Service] Connecting to Supabase (Using ML-Native Schema)...")
        self.client: Client = create_client(url, key)

    def load_registered_units(self):
        """ Fetch all authorized units from the resources table to validate incoming telemetry """
        try:
            res = self.client.table('resources').select('id, type, name').execute()
            # Returns a fast lookup dictionary
            return {u['id']: {"type": u['type'], "name": u['name']} for u in res.data}
        except Exception:
            # Fallback for hackathon testing if resources table isn't populated yet
            return {
                "U-104": {"type": "fire_truck", "name": "Engine 4"},
                "U-108": {"type": "fire_truck", "name": "Ladder 2"},
                "U-203": {"type": "rescue", "name": "Rescue 3"},
                "U-401": {"type": "ambulance", "name": "Medic 7"}
            }

    def find_nearby_incident(self, lat, lng, time_str, radius_m=500):
        """ Calls the PostgreSQL RPC function for blazing-fast PostGIS Spatial Deduplication. """
        response = self.client.rpc('find_nearby_incident', {
            'p_lat': lat,
            'p_lng': lng,
            'p_radius_meters': radius_m
        }).execute()
        
        if response.data and len(response.data) > 0:
            rec = response.data[0]
            rec['location'] = {'lat': rec.pop('latitude'), 'lng': rec.pop('longitude')}
            return rec
        return None

    def create_incident(self, payload_id, category, severity, lat, lng):
        """ Inserts a brand new Incident Card """
        # Map 1-5 severity to text for DB constraint
        sev_str = "LOW" if severity <= 2 else "MEDIUM" if severity == 3 else "HIGH" if severity == 4 else "CRITICAL"
        
        inc = {
            "incident_type": str(category).upper(),
            "description": "Auto-generated by ML Pipeline",
            "source": "ML_PIPELINE", # Required NOT NULL constraint
            "severity": sev_str,     # Required CHECK constraint ('HIGH', 'LOW', etc)
            "latitude": lat,
            "longitude": lng,
            "status": "ACTIVE",      # Required CHECK constraint ('ACTIVE')
            "source_events": [payload_id],
        }
        response = self.client.table('incidents').insert(inc).execute()
        rec = response.data[0]
        # Return mapped dict for frontend
        rec['location'] = {'lat': rec.pop('latitude'), 'lng': rec.pop('longitude')}
        return rec

    def update_incident(self, incident_id, payload_id, new_severity):
        """ Deduplication: Append the new payload ID and escalate severity if needed """
        current = self.client.table('incidents').select('source_events, severity').eq('id', incident_id).execute().data[0]
        current['source_events'].append(payload_id)
        
        # Map current string to number for comparison
        sev_map = {"LOW": 1, "MEDIUM": 3, "HIGH": 4, "CRITICAL": 5}
        current_sev_num = sev_map.get(current['severity'], 1)
        max_sev_num = max(current_sev_num, new_severity)
        
        # Map back to string
        final_sev_str = "LOW" if max_sev_num <= 2 else "MEDIUM" if max_sev_num == 3 else "HIGH" if max_sev_num == 4 else "CRITICAL"
        
        response = self.client.table('incidents').update({
            "source_events": current['source_events'],
            "severity": final_sev_str,
            "updated_at": datetime.utcnow().isoformat()
        }).eq('id', incident_id).execute()
        
        rec = response.data[0]
        rec['location'] = {'lat': rec.pop('latitude', 0.0), 'lng': rec.pop('longitude', 0.0)}
        return rec
        
    def save_recommendations(self, incident_id, recommended_units, ai_text):
        """ Attaches the Human-in-the-Loop recommendations to the Incident Card """
        response = self.client.table('incidents').update({
            "recommended_units": recommended_units,
            "ai_recommendation": ai_text
        }).eq('id', incident_id).execute()
        return response.data[0]
