import os
from supabase import create_client, Client
from dotenv import load_dotenv

load_dotenv()
client: Client = create_client(os.environ.get("SUPABASE_URL"), os.environ.get("SUPABASE_KEY"))

try:
    inc = {
        "incident_type": "FIRE",
        "description": "Generated by ML",
        "source": "ML_PIPELINE",
        "severity": "HIGH",
        "latitude": 10.0,
        "longitude": 20.0,
        "status": "ACTIVE",
        "source_events": ["123"]
    }
    res = client.table('incidents').insert(inc).execute()
    print("SUCCESS")
    print(res)
except Exception as e:
    print(e)
