import { Incident, ResponseUnit, ActivityEvent, MetricCardData } from "./types";

export const INITIAL_INCIDENTS: Incident[] = [
  {
    id: "INC-4821",
    type: "Structure Fire",
    severity: "Critical",
    location: "14 Meridian Ave",
    coordinates: { lat: 23.0338, lon: 72.562 },
    timeReceived: "08:14 AM",
    timeAgo: "14m ago",
    assignedUnits: ["Engine 4", "Ladder 2"],
    status: "En route",
    incidentCommander: "Capt. Rachel Vance (Station 4)",
    hydrantStatus: "Adequate (950 GPM)",
    evacuationRadiusMeters: 150,
    callerReport:
      "Heavy black smoke billowing from second-floor commercial bakery with residential lofts above. Multiple occupants seen on balcony.",
    aiRecommendation:
      "Smoke conditions are worsening on the north elevation. Recommend staging a second medic unit and closing Meridian Avenue between 3rd and 5th.",
    duplicateReportsCount: 4,
    timeline: [
      { time: "08:14 AM", description: "First 911 call logged from store manager", actor: "CAD Dispatch" },
      { time: "08:16 AM", description: "Engine 4 & Ladder 2 dispatched code 3", actor: "Supervisor Miller" },
      { time: "08:18 AM", description: "Duplicate reports consolidated; thermal feed activated", actor: "AI Telemetry" },
      { time: "08:22 AM", description: "Engine 4 en route, ETA 3 minutes", actor: "Mobile Data Terminal" },
    ],
  },
  {
    id: "INC-4819",
    type: "Vehicle Collision",
    severity: "High",
    location: "M8 Eastbound, Exit 12",
    coordinates: { lat: 23.045, lon: 72.54 },
    timeReceived: "08:02 AM",
    timeAgo: "26m ago",
    assignedUnits: ["Rescue 3", "Medic 7"],
    status: "On scene",
    incidentCommander: "Lt. Marcus Brody (EMS Dist 2)",
    hydrantStatus: "Limited (420 GPM)",
    evacuationRadiusMeters: 50,
    callerReport: "Three-vehicle pileup blocking two lanes. One hybrid SUV smoking with suspected battery intrusion.",
    aiRecommendation:
      "Recommend dispatching HazMat 1 for battery containment protocol. Divert M8 Eastbound traffic to alternate arterial 14A.",
    duplicateReportsCount: 7,
    timeline: [
      { time: "08:02 AM", description: "Automated collision telemetry trigger received", actor: "eCall Gateway" },
      { time: "08:05 AM", description: "Rescue 3 and Medic 7 assigned", actor: "Supervisor Miller" },
      { time: "08:17 AM", description: "Units on scene. Extrication initiated for driver 1", actor: "Rescue 3 Officer" },
      { time: "08:24 AM", description: "Escalation threshold reached: incident INC-4819", actor: "Ops Alert System" },
    ],
  },
  {
    id: "INC-4817",
    type: "Infrastructure / Flood",
    severity: "Medium",
    location: "Hawthorne Tunnel",
    coordinates: { lat: 23.018, lon: 72.58 },
    timeReceived: "07:45 AM",
    timeAgo: "43m ago",
    assignedUnits: ["Public Works 2"],
    status: "Assessing",
    incidentCommander: "Foreman Douglas Chen",
    hydrantStatus: "Unverified",
    evacuationRadiusMeters: 0,
    callerReport: "Storm runoff drainage backflow causing 18 inches of standing water in westbound transit bore.",
    aiRecommendation:
      "Recommend engaging high-capacity stormwater pumps at sump station 3 and restricting commercial vehicles.",
    duplicateReportsCount: 2,
    timeline: [
      { time: "07:45 AM", description: "Transit authority camera alarm triggered", actor: "Metro DOT" },
      { time: "07:55 AM", description: "Public Works 2 deployed with sump equipment", actor: "CAD Dispatch" },
      { time: "08:12 AM", description: "Initial water level reading logged: 19.4 inches", actor: "Field Unit" },
    ],
  },
  {
    id: "INC-4814",
    type: "Gas Leak",
    severity: "High",
    location: "88 Orchard Street",
    coordinates: { lat: 23.029, lon: 72.55 },
    timeReceived: "07:31 AM",
    timeAgo: "57m ago",
    assignedUnits: ["HazMat 1"],
    status: "Dispatched",
    incidentCommander: "Specialist Elena Gomez",
    hydrantStatus: "Adequate (950 GPM)",
    evacuationRadiusMeters: 100,
    callerReport: "Strong odor of mercaptan/natural gas reported by elementary school maintenance staff near boiler intake.",
    aiRecommendation:
      "Recommend 100m perimeter perimeter check and immediate gas main valve isolation coordination with City Gas grid.",
    duplicateReportsCount: 3,
    timeline: [
      { time: "07:31 AM", description: "School administration report received", actor: "CAD Dispatch" },
      { time: "07:36 AM", description: "HazMat 1 unit mobilized with sniffing array", actor: "Supervisor Miller" },
      { time: "07:48 AM", description: "City Gas emergency valve technician en route", actor: "External Agency" },
    ],
  },
  {
    id: "INC-4811",
    type: "Medical Emergency",
    severity: "Medium",
    location: "Central Station Concourse",
    coordinates: { lat: 23.0225, lon: 72.5714 },
    timeReceived: "07:18 AM",
    timeAgo: "1h 10m ago",
    assignedUnits: ["Medic 4"],
    status: "Transporting",
    incidentCommander: "Paramedic S. Patel",
    hydrantStatus: "Adequate (950 GPM)",
    evacuationRadiusMeters: 0,
    callerReport: "62-year-old passenger collapsed on platform 3 with cardiac distress; AED deployed by transit officer.",
    aiRecommendation:
      "Recommend pre-notifying Metro Memorial Trauma Center ER for incoming STEMI cath lab prep.",
    duplicateReportsCount: 1,
    timeline: [
      { time: "07:18 AM", description: "Platform emergency call box initiated", actor: "Transit Police" },
      { time: "07:22 AM", description: "Medic 4 on scene; rhythm converted via AED", actor: "Medic 4" },
      { time: "07:44 AM", description: "Patient stabilized, en route to hospital", actor: "Medic 4" },
    ],
  },
  {
    id: "INC-4809",
    type: "Power Grid Surge",
    severity: "Medium",
    location: "Substation 4, West Sector",
    coordinates: { lat: 23.055, lon: 72.52 },
    timeReceived: "06:50 AM",
    timeAgo: "1h 38m ago",
    assignedUnits: ["Utility 1"],
    status: "En route",
    incidentCommander: "Eng. Keith Reynolds",
    hydrantStatus: "Unverified",
    evacuationRadiusMeters: 80,
    callerReport: "Transformer arc flash spotted during automated load shedding sequence.",
    aiRecommendation:
      "Recommend rerouting distribution feed from Substation 6 to avoid hospital district brownout.",
    duplicateReportsCount: 2,
    timeline: [
      { time: "06:50 AM", description: "SCADA supervisory alert fired", actor: "Grid SCADA" },
      { time: "07:05 AM", description: "Utility crew 1 dispatched for thermal imaging inspect", actor: "CAD Dispatch" },
    ],
  },
  {
    id: "INC-4805",
    type: "Infrastructure / Flood",
    severity: "Low",
    location: "402 Pine Boulevard",
    coordinates: { lat: 23.012, lon: 72.56 },
    timeReceived: "06:15 AM",
    timeAgo: "2h 13m ago",
    assignedUnits: ["Public Works 4"],
    status: "Pending",
    incidentCommander: "Unassigned",
    hydrantStatus: "Limited (420 GPM)",
    evacuationRadiusMeters: 0,
    callerReport: "Subsurface main leak seeping through curb seam into pedestrian lane.",
    aiRecommendation:
      "Low immediate hazard. Schedule inspection crew following morning peak traffic.",
    duplicateReportsCount: 1,
    timeline: [
      { time: "06:15 AM", description: "Citizen 311 app report submitted with photo", actor: "Municipal 311" },
    ],
  },
];

export const INITIAL_UNITS: ResponseUnit[] = [
  {
    id: "U-104",
    callsign: "Engine 4",
    type: "Fire & Rescue",
    status: "En route",
    currentLocation: "West District / Station 4",
    coordinates: { lat: 23.031, lon: 72.568 },
    assignedIncidentId: "INC-4821",
    crewCount: 4,
    vehicleType: "Type 1 Heavy Pumper (1500 GPM)",
    equipmentStatus: "Full SCBA & Thermal Gear",
    batteryFuelPct: 92,
  },
  {
    id: "U-108",
    callsign: "Ladder 2",
    type: "Fire & Rescue",
    status: "En route",
    currentLocation: "North Sector / Station 2",
    coordinates: { lat: 23.042, lon: 72.558 },
    assignedIncidentId: "INC-4821",
    crewCount: 4,
    vehicleType: "100ft Aerial Platform Truck",
    equipmentStatus: "Ventilation Saws & Rescue Basket",
    batteryFuelPct: 88,
  },
  {
    id: "U-203",
    callsign: "Rescue 3",
    type: "Fire & Rescue",
    status: "On scene",
    currentLocation: "M8 Corridor (Exit 12)",
    coordinates: { lat: 23.045, lon: 72.54 },
    assignedIncidentId: "INC-4819",
    crewCount: 5,
    vehicleType: "Heavy Technical Rescue Rig",
    equipmentStatus: "Hydraulic Jaws, Air Bags & Stabilization",
    batteryFuelPct: 76,
  },
  {
    id: "U-307",
    callsign: "Medic 7",
    type: "Medical / EMS",
    status: "On scene",
    currentLocation: "M8 Corridor (Exit 12)",
    coordinates: { lat: 23.045, lon: 72.54 },
    assignedIncidentId: "INC-4819",
    crewCount: 2,
    vehicleType: "ALS Critical Transport Unit",
    equipmentStatus: "Zoll X Series Monitor, Lucas CPR",
    batteryFuelPct: 84,
  },
  {
    id: "U-304",
    callsign: "Medic 4",
    type: "Medical / EMS",
    status: "Transporting",
    currentLocation: "Downtown Arterial (Transit Bore)",
    coordinates: { lat: 23.024, lon: 72.566 },
    assignedIncidentId: "INC-4811",
    crewCount: 2,
    vehicleType: "ALS Ambulance",
    equipmentStatus: "Telemetry Link Active",
    batteryFuelPct: 89,
  },
  {
    id: "U-401",
    callsign: "HazMat 1",
    type: "HazMat & Special",
    status: "En route",
    currentLocation: "88 Orchard Sector",
    coordinates: { lat: 23.029, lon: 72.55 },
    assignedIncidentId: "INC-4814",
    crewCount: 3,
    vehicleType: "Chemical Response & Decon Van",
    equipmentStatus: "Multi-Gas Sensors & Level A Suits",
    batteryFuelPct: 94,
  },
  {
    id: "U-502",
    callsign: "Public Works 2",
    type: "Public Works",
    status: "On scene",
    currentLocation: "Hawthorne Underpass",
    coordinates: { lat: 23.018, lon: 72.58 },
    assignedIncidentId: "INC-4817",
    crewCount: 3,
    vehicleType: "High-Volume Mobile Sump Truck",
    equipmentStatus: "3x 4-inch Submersible Pumps",
    batteryFuelPct: 80,
  },
  {
    id: "U-101",
    callsign: "Engine 1",
    type: "Fire & Rescue",
    status: "Available",
    currentLocation: "Central HQ / Station 1",
    coordinates: { lat: 23.0225, lon: 72.5714 },
    crewCount: 4,
    vehicleType: "Type 1 Triple Combination Pumper",
    equipmentStatus: "Ready for Dispatch",
    batteryFuelPct: 100,
  },
  {
    id: "U-302",
    callsign: "Medic 2",
    type: "Medical / EMS",
    status: "Available",
    currentLocation: "District Hospital Base",
    coordinates: { lat: 23.0396, lon: 72.5317 },
    crewCount: 2,
    vehicleType: "Paramedic Rescue Unit",
    equipmentStatus: "Restocked and Ready",
    batteryFuelPct: 98,
  },
  {
    id: "U-612",
    callsign: "Patrol Cruiser 12",
    type: "Police Support",
    status: "Available",
    currentLocation: "Meridian Sector Patrol",
    coordinates: { lat: 23.03, lon: 72.565 },
    crewCount: 2,
    vehicleType: "AWD Tactical Interceptor",
    equipmentStatus: "First Aid & Perimeter Spike Strips",
    batteryFuelPct: 91,
  },
  {
    id: "U-618",
    callsign: "Patrol Cruiser 18",
    type: "Police Support",
    status: "Available",
    currentLocation: "East River Crossing",
    coordinates: { lat: 23.021, lon: 72.578 },
    crewCount: 2,
    vehicleType: "AWD Tactical Interceptor",
    equipmentStatus: "Active Mobile CAD",
    batteryFuelPct: 86,
  },
  {
    id: "U-701",
    callsign: "Drone Recon Alpha",
    type: "HazMat & Special",
    status: "Available",
    currentLocation: "Metro Emergency Roof Pad",
    coordinates: { lat: 23.025, lon: 72.569 },
    crewCount: 1,
    vehicleType: "Heavy Quadcopter Thermal FLIR",
    equipmentStatus: "4K Optical / 640x512 Radiometric",
    batteryFuelPct: 100,
  },
];

export const INITIAL_ACTIVITY: ActivityEvent[] = [
  {
    id: "act-1",
    timestamp: "08:24 AM",
    title: "Escalation threshold reached: incident INC-4819",
    description: "Collision incident on M8 exceeded 20m unassisted queue limit. Auto-alerted supervisor.",
    type: "escalation",
    severity: "High",
    relatedIncidentId: "INC-4819",
  },
  {
    id: "act-2",
    timestamp: "08:22 AM",
    title: "Engine 4 acknowledged dispatch",
    description: "Code 3 response acknowledged by Captain Vance. Heading west via Meridian.",
    type: "dispatch",
    relatedIncidentId: "INC-4821",
  },
  {
    id: "act-3",
    timestamp: "08:18 AM",
    title: "Duplicate report consolidated into INC-4821",
    description: "4 independent caller reports merged into single active fire incident.",
    type: "system",
    relatedIncidentId: "INC-4821",
  },
  {
    id: "act-4",
    timestamp: "08:17 AM",
    title: "Medic 7 arrived on scene",
    description: "Medic 7 GPS telemetry registered geo-fence entry at M8 Eastbound Exit 12.",
    type: "arrival",
    relatedIncidentId: "INC-4819",
  },
  {
    id: "act-5",
    timestamp: "08:05 AM",
    title: "Road sensor feed restored",
    description: "DOT arterial sensor node #44-A telemetry reconnected via mesh failover.",
    type: "resource",
  },
];

export const OVERVIEW_METRICS: MetricCardData[] = [
  {
    title: "Active Incidents",
    value: 24,
    change: "+3 since 08:00",
    iconName: "Flame",
    trend: [18, 19, 21, 21, 22, 24],
    statusColor: "coral",
  },
  {
    title: "Critical / High Priority",
    value: 7,
    change: "3 require supervisor action",
    iconName: "AlertTriangle",
    trend: [4, 5, 5, 6, 6, 7],
    statusColor: "amber",
  },
  {
    title: "Teams Deployed",
    value: 18,
    change: "82% field capacity",
    iconName: "ShieldAlert",
    trend: [14, 15, 16, 17, 18, 18],
    statusColor: "blue",
  },
  {
    title: "Median Dispatch Time",
    value: "06:42",
    change: "Target: under 08:00 (-18s)",
    iconName: "Clock",
    trend: [7.2, 7.0, 6.8, 6.7, 6.7, 6.7],
    statusColor: "green",
  },
];

export const RESOURCE_AVAILABILITY_STATS = [
  {
    category: "Fire & Rescue",
    available: 12,
    total: 18,
    warning: false,
    color: "bg-orange-500",
    description: "6 pumpers, 2 ladders deployed",
  },
  {
    category: "Medical / EMS",
    available: 7,
    total: 11,
    warning: false,
    color: "bg-blue-500",
    description: "4 ALS units active in transport",
  },
  {
    category: "Police Support",
    available: 9,
    total: 14,
    warning: false,
    color: "bg-indigo-500",
    description: "5 cruisers assigned to cordons",
  },
  {
    category: "Utility & Public Works",
    available: 4,
    total: 6,
    warning: true,
    color: "bg-amber-500",
    description: "Constrained: 2 pumping crews deployed",
  },
];

export const GEOAPIFY_API_KEY = "481397a246044ce3a39cbbd9a2352474";
export const DEFAULT_CENTER = {
  lat: 23.0225,
  lon: 72.5714,
  label: "Metro Command District (Central)",
};
